spring:
  cache:
    type: redis
  redis:
    port: ${REDIS_PORT:6379}
    username: ${REDIS_USERNAME:master}
    password: ${REDIS_PASSWD:ARLepton1234}
    sentinel:
      master: mymaster
      nodes:
        - redis-sentinel-0.redis-sentinel:5000
        - redis-sentinel-0.redis-sentinel:5000
        - redis-sentinel-0.redis-sentinel:5000
    lettuce:
      shutdown-timeout: 200ms

