{{- if .Values.configmap.create -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
    release: {{ .Release.Name }}
data:
  REDIS_MODE: {{ .Values.configmap.data.redisMode | quote }}
  REDIS_HOST: {{ .Values.configmap.data.redisHost | quote }}
  REDIS_PORT: {{ .Values.configmap.data.redisPort | quote }}
  SENTINEL_PORT: {{ .Values.configmap.data.sentinelPort | quote }}
  REDIS_USER: {{ .Values.configmap.data.redisUser | quote }}
  REDIS_PASSWD: {{ .Values.configmap.data.redisPasswd | quote }}
{{- end -}}